# This is a basic workflow to help you get started with Actions

name: PULL

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "curl"
  curl:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: get file
        env:
           REPO_TOKE: ${{ secrets.REPO_TOKEN }}
        run: |
          curl -H "Authorization: token ${REPO_TOKE}" -H "Accept: application/vnd.github.v3.raw" -O https://api.github.com/repos/wolviex/mactools/contents/kc_proxy.pac
      
